server:
  port: 1001

spring:
  application:
    name: hls-provider-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.105.72.38:3306/hls?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Hlsfjl123!

eureka:
  client:
    #表示是否将自己注册进eureka server 默认是true
    register-with-eureka: true
    #是否从eurekaServer 注册中心 抓取已有的注册信息 默认是true  单节点无所谓  集群必须设置为true 才能配合ribbon实现负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: provider1001
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package:  hls.framework.persistent
